version: '3'
services:
  watchCat:
    image: salero33/watchcat:latest
    container_name: watchCat
    restart: unless-stopped
    volumes:
      - ./config:/home/watchcat/config/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Zurich
    labels:
      - "watchCat=True"
      - "watchCat.group=default"