version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: test_nginx
        restart: unless-stopped
        labels:
        - "watchCat=True"
        - "watchCat.group=default test"

    mysql:
        image: mysql:latest
        container_name: test_mysql
        restart: unless-stopped
        labels:
        - "watchCat=True"